# Pre-commit hooks for Poon AI Service
# See https://pre-commit.com for more information

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: debug-statements
      - id: check-docstring-first

  # Python code formatting and linting with Ruff (focused on new architecture)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      # Linter
      - id: ruff
        files: ^(src/|tests/|scripts/)
        args: [--fix, --exit-non-zero-on-fix]
      # Formatter
      - id: ruff-format
        files: ^(src/|tests/|scripts/)

  # Type checking with MyPy (disabled temporarily for migration)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.7.1
  #   hooks:
  #     - id: mypy
  #       files: ^src/
  #       additional_dependencies:
  #         - pydantic>=2.0.0
  #         - fastapi>=0.100.0
  #         - types-requests
  #       args: [--ignore-missing-imports, --no-strict-optional]

  # YAML formatting (simplified)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types: [yaml]
        exclude: ^bruno/

# Configuration for specific tools
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
